#!/usr/bin/env python3
"""21_make_tables.py — Generate every numeric table in the manuscript from
results/paper_numbers.json. main.tex and supplementary.tex \\input these
fragments; no table number is ever typed by hand.

Outputs (paper/tables/):
  tab_desc.tex      Table: panel + topology (Panel A/B)
  tab_main.tex      Table: fixed split + multi-seed increments
  tab_leak.tex      Table: leakage dose-response
  tab_grid_full.tex Supplementary Table S1: full construction grid
"""
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
J = json.load(open(f"{BASE}/results/paper_numbers.json"))
OUT = f"{BASE}/paper/tables"
os.makedirs(OUT, exist_ok=True)


def w(name, content):
    with open(f"{OUT}/{name}", "w") as f:
        f.write("% AUTO-GENERATED by code/21_make_tables.py from results/paper_numbers.json\n"
                "% DO NOT EDIT BY HAND — regenerate instead.\n" + content)
    print("wrote", name)


def n(x):  # thousands with LaTeX comma
    return f"{x:,}".replace(",", "{,}")


# ---------------- tab_desc ----------------
P, NP, T = J["panel"], J["network_periods"], J["topology"]
e, l = P["early"], P["late"]
np1, np2 = NP["2004_2013"], NP["2014_2024"]
rows_b = "\n".join(
    f"{y} & {n(v['nodes'])} & {n(v['edges'])} & {v['density_e4']:.2f} & "
    f"{v['mean_deg']:.1f} / {v['max_deg']} & {v['clustering']:.3f} & "
    f"{v['giant_pct']:.1f} & {n(v['components'])} & {v['fraud_firms']} \\\\"
    for y, v in sorted(T.items()))
w("tab_desc.tex", f"""\\begin{{table}}[H]
\\centering
\\caption{{Panel and network description. Panel A: firm-year panel by period (network statistics are annual snapshot averages; fraud-firm counts are firms with fraud revealed before the snapshot year). Panel B: topology of the interlock graph at selected snapshots (density scaled by $10^4$; Giant \\% is the share of nodes in the largest connected component).}}
\\small
\\textbf{{Panel A: firm-year panel}}\\\\[2pt]
\\begin{{tabular}}{{lcc}}
\\toprule
 & 2004--2013 & 2014--2024 \\\\
\\midrule
Firm years in panel & {n(e['firm_years'])} & {n(l['firm_years'])} \\\\
Connected registrants (avg.\\ snapshot) & {n(np1['avg_firms'])} & {n(np2['avg_firms'])} \\\\
Interlock edges (avg.\\ snapshot) & {n(np1['avg_edges'])} & {n(np2['avg_edges'])} \\\\
Past-revealed fraud firms (start $\\to$ end) & {np1['fraud_start']} $\\to$ {np1['fraud_end']} & {np2['fraud_start']} $\\to$ {np2['fraud_end']} \\\\
Fraud-label base rate & {e['base_pct']:.2f}\\% ({e['pos']} pos) & {l['base_pct']:.2f}\\% ({l['pos']} pos) \\\\
\\bottomrule
\\end{{tabular}}\\\\[8pt]
\\textbf{{Panel B: graph topology by snapshot}}\\\\[2pt]
\\resizebox{{\\textwidth}}{{!}}{{%
\\begin{{tabular}}{{lcccccccc}}
\\toprule
Year & Nodes & Edges & Density & Mean/Max deg. & Clustering & Giant \\% & Components & Fraud \\\\
\\midrule
{rows_b}
\\bottomrule
\\end{{tabular}}%
}}
\\label{{tab:desc}}
\\end{{table}}
""")

# ---------------- tab_main ----------------
F, S = J["fixed_split"], J["seeds"]
w("tab_main.tex", f"""\\begin{{table}}[H]
\\centering
\\caption{{Fixed temporal split (train 2004--2017, test 2018--2023; 45 test positives), fraud label. Left: point estimates. Right: increment of FIN$+$NET4 over FIN across ten seeds.}}
\\begin{{tabular}}{{lcc@{{\\qquad}}lcc}}
\\toprule
Feature set & ROC & PR & Model & Mean $\\Delta$ROC & Seed SD \\\\
\\midrule
FIN (28 items) & {F['FIN']['roc']:.4f} & {F['FIN']['pr']:.4f} & RUSBoost & ${S['rusboost']['mean']:+.3f}$ & {S['rusboost']['sd']:.3f} \\\\
FIN$+$NET4 & {F['FIN_NET4']['roc']:.4f} & {F['FIN_NET4']['pr']:.4f} & Grad.\\ boosting & ${S['hgb']['mean']:+.3f}$ & {S['hgb']['sd']:.3f} \\\\
FIN$+$NET7 & {F['FIN_NET7']['roc']:.4f} & {F['FIN_NET7']['pr']:.4f} & Logistic & ${S['logit']['mean']:+.3f}$ & --- \\\\
\\bottomrule
\\end{{tabular}}
\\label{{tab:main}}
\\end{{table}}
""")

# ---------------- tab_leak ----------------
D = J["dose_response"]
w("tab_leak.tex", f"""\\begin{{table}}[H]
\\centering
\\caption{{Leakage dose-response. One pipeline, one model (RUSBoost), fixed split, fraud label; only the reveal-date discipline of the exposure feature varies.}}
\\begin{{tabular}}{{lc}}
\\toprule
Exposure feature construction & ROC-AUC \\\\
\\midrule
Leak-free (reveal $< t$) & {D['clean']:.3f} \\\\
Reveal $< t+1$ & {D['t1']:.3f} \\\\
Reveal $< t+2$ & {D['t2']:.3f} \\\\
Reveal $< t+3$ & {D['t3']:.3f} \\\\
All fraud, reveal dates ignored & {D['all']:.3f} \\\\
$+$ own future revelation flag & \\textbf{{{D['self_leak']:.3f}}} \\\\
\\bottomrule
\\end{{tabular}}
\\label{{tab:leak}}
\\end{{table}}
""")

# ---------------- tab_grid_full (Supplementary S1) ----------------
G = J["grid_full"]
labels = [("3-year", "unweighted"), ("3-year", "weighted"),
          ("4-year", "unweighted"), ("4-year", "weighted"),
          ("5-year", "unweighted"), ("5-year", "weighted")]
rows = "\n".join(
    f"{wl} & {el} & {c['fin']:.4f} & {c['net']:.4f} & ${c['d']:+.4f}$ \\\\"
    for (wl, el), c in zip(labels, G))
w("tab_grid_full.tex", f"""\\begin{{table}}[h!]
\\centering
\\caption*{{\\textbf{{Supplementary Table S1.}} Full construction grid (fixed split, fraud label, 45 test positives, RUSBoost, seed 42). The FIN baseline varies across window rows because the merged sample changes with network coverage.}}
\\begin{{tabular}}{{llccc}}
\\toprule
Window & Edges & FIN ROC & FIN$+$NET4 ROC & $\\Delta$ \\\\
\\midrule
{rows}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
""")
print("all tables generated from JSON")
